AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This template creates the IAM service role used by AWS Backup.
  It should be deployed to a single AWS region in the central AWS Backup vault account.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: AWS Backup Configuration
        Parameters:
          - pCrossAccountBackupRole
      -
        Label:
          default: AWS Backup Tags
        Parameters:
          - BusinessUnit
          - CostCenter
          - Owner

    ParameterLabels:
      pCrossAccountBackupRole:
        default: Enter an IAM Role Name
      BusinessUnit:
        default: Enter the business unit that owns the resources created by this stack.
      CostCenter:
        default: Enter the cost center for the resources created by this stack.
      Owner:
        default: Enter the owner for the resources created by this stack.



Parameters:
  pCrossAccountBackupRole:
    Type: String
    Description: This is the IAM role name for the cross-account backup role that carries out the backup activities.
    Default:  AWSBackupSolutionCentralAccountRole
  # Customer Specific Tags - Example
  BusinessUnit:
    Description: Business Unit Name
    Type: String
    MinLength: '1'
    MaxLength: '255'
    AllowedValues:
      - Marketing
      - Engineering
      - R&D
    ConstraintDescription: Must be a valid business unit
    Default:  Engineering
  CostCenter:
    Description: Cost Center for AWS Services
    Type: String
    MinLength: '1'
    MaxLength: '255'
    Default:  '00000'
  Owner:
    Description: Email address of application owner
    Type: String
    Default:  backupandrecoveryowner@example.com


Resources:
  rOrgAccountBackupRoleCentral:
    Type: "AWS::IAM::Role"
    Properties:
      Description: Allows AWS Backup to access AWS services
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - backup.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup
        - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForRestores
      RoleName: !Sub ${pCrossAccountBackupRole}
      Tags:
        - Key: BusinessUnit
          Value: !Ref BusinessUnit
        - Key: CostCenter
          Value: !Ref CostCenter
        - Key: Owner
          Value: !Ref Owner

Outputs:
  oOrgAccountBackupRoleCentral:
    Value: !Ref rOrgAccountBackupRoleCentral
